<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/WukongBench.Core/WukongBench.Core.csproj" />
    <ProjectReference Include="../../src/WukongBench/WukongBench.csproj" />
  </ItemGroup>
</Project>
